### ISSUE TITLE
Fix tree issues

### ISSUE THREAD

**Issue by jbergstroem** [gentoo/proxy-maintainers#26] opened 2015-04-06 00:08 UTC
Every PR test will fail since vlc seems to have some invalid flags that repoman is angry about. Its unfortunately been like this for a while. Can some repo admin sync against gentoo-x86 (assuming this will fix it)? Thanks.

For more details, see for instance this travis output: https://travis-ci.org/gentoo/proxy-maintainers/builds/56829475

**Comment by jbergstroem** [comment] 2015-04-06 00:23
Suggestion: Perhaps avoid repoman full? One package otherwise gets penalised for issues related to others.

**Comment by hwoarang** [comment] 2015-04-11 09:12
I guess the problem is with VLC? Yes I believe that repoman full is too expensive. I am not sure if there is another way to fix it though.

**Comment by mrueg** [comment] 2015-04-11 12:37
We probably should think about moving over to https://github.com/gentoo/gentoo-portage-rsync-mirror

**Comment by jbergstroem** [comment] 2015-04-12 22:44
@mrueg I'd be ok with that. Do I just open PR's there instead?

**Comment by hwoarang** [comment] 2015-04-19 09:24
It's up to you how you want to maintain your package.

**Comment by jbergstroem** [comment] 2015-04-19 23:49
@hwoarang sure, but this is more about making the life of a reviewer/proxy easier.

**Comment by hwoarang** [comment] 2015-04-20 18:29
It's really up to you. There is not a clear workflow. Either way, the package will find its way to the tree. So it's up to you. As far as I know, both repositories are being monitored by (different set?) of developers so I wouldn't worry too much. If 'path A' does not work for you, you can always choose 'path B' and so forth.

I am closing this since we went a bit off-topic ;)

**Closed by hwoarang** 2015-04-20 18:29 UTC
Labels: enhancement
